# Generated by Django 3.1.1 on 2020-11-18 02:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('7 Rizal', '7 Rizal'), ('7 Bonifacio', '7 Bonifacio'), ('7 Del Pilar', '7 Del Pilar'), ('8 Nakpil', '8 Nakpil'), ('8 Bernal', '8 Bernal'), ('8 Joaquin', '8 Joaquin'), ('9 Shakespeare', '9 Shakespeare'), ('9 Dickens', '9 Dickens'), ('9 Twain', '9 Twain'), ('10 Einstein', '10 Einstein'), ('10 Franklin', '10 Franklin'), ('10 Newton', '10 Newton'), ('11 ABM', '11 ABM'), ('11 GAS/HUMSS', '11 GAS/HUMSS'), ('11 STEM', '11 STEM'), ('12 ABM', '12 ABM'), ('12 GAS/HUMSS', '12 GAS/HUMSS'), ('12 STEM', '12 STEM')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='Grade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
