# Generated by Django 3.1.1 on 2020-11-18 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201118_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Quarter',
            field=models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('1', 'Third Quarter'), ('1', 'Fourth Quarter')], default=django.utils.timezone.now, max_length=100, verbose_name='What Quarter ?'),
            preserve_default=False,
        ),
    ]
