# Generated by Django 3.1.5 on 2021-01-25 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False, verbose_name='Block Access')),
            ],
        ),
        migrations.AlterField(
            model_name='firstquarter',
            name='Grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='firstquarter',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstgrade', to='api.student'),
        ),
        migrations.AlterField(
            model_name='fourthquarter',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourthgrade', to='api.student'),
        ),
        migrations.AlterField(
            model_name='secondquarter',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondgrade', to='api.student'),
        ),
        migrations.AlterField(
            model_name='thirdquarter',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdgrade', to='api.student'),
        ),
    ]
