# Generated by Django 3.1.5 on 2021-01-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210125_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='JuniorHigh',
        ),
    ]
