# Generated by Django 3.1.5 on 2021-01-25 01:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210125_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorHigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('LRN', models.CharField(max_length=100, unique=True)),
                ('Status', models.BooleanField(default=False, verbose_name='Block Access')),
                ('Section', models.CharField(choices=[('11 ABM', '11 ABM'), ('11 GAS/HUMSS', '11 GAS/HUMSS'), ('11 STEM', '11 STEM'), ('12 ABM', '12 ABM'), ('12 GAS/HUMSS', '12 GAS/HUMSS'), ('12 STEM', '12 STEM')], max_length=100)),
                ('Quarter', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('1', 'Third Quarter'), ('1', 'Fourth Quarter')], max_length=100, verbose_name='What Quarter ?')),
            ],
        ),
        migrations.CreateModel(
            name='SHSecondQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondgrade', to='api.seniorhigh')),
            ],
        ),
        migrations.CreateModel(
            name='SHFirstQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstgrade', to='api.seniorhigh')),
            ],
        ),
    ]
